### PR TITLE
Add build CI

### PR DESCRIPTION
**Pull request by illusion0001**
Generates the stylesheet and push it to the repository (if there are changes) when running from workflow dispatch.
https://github.com/illusion0001/twemoji-amazing/commit/5da3d4002c4ccdb2bdf0ea318fc3e72146570d22

### CODE REVIEW

**Comment by SebastianAigner** [comment]
Whoa - super cool, @illusion0001!

Think you can automate the generation of the releases, https://github.com/SebastianAigner/twemoji-amazing/releases/tag/v1.0.0, from tagged commits as well? That’d be amazing!

**Comment by illusion0001** [comment]
@SebastianAigner https://github.com/illusion0001/twemoji-amazing/releases/tag/1.57

**Comment by illusion0001** [comment]
Also combined test and build into a single workflow

**Comment by SebastianAigner** [comment]
Thank you so much for your contribution, @illusion0001 – that'll make the workflow for developing and releasing twemoji-amazing much more comfortable in the future! 🔥

**Comment by illusion0001** [comment]
Thanks for merging! To get actions to push a release, all you have to do is head over to the actions tab, select the generate CSS workflow and the green run button.

Screenshot_20220405_054811

**Pull request merged**
